[package]
name = "audioscope"
version = "0.1.0"
authors = ["delu <davidelu93@gmail.com>"]

[dependencies]
toml = "*"
rustc-serialize = "*"
glium = "*"
portaudio = "*"
num = "*"
rustfft = { git = "https://github.com/awelkie/RustFFT" }
